public enum CollisionType {
    PARTICLE,
    LEFT_HORIZONTAL_WALL,
    RIGHT_HORIZONTAL_WALL,
    LEFT_VERTICAL_WALL,
    MIDDLE_WALL,
    RIGHT_VERTICAL_WALL,
    UPPER_MIDDLE_CORNER,
    LOWER_MIDDLE_CORNER;

}